### ISSUE TITLE
Userscript: Send to archive not showing

### ISSUE THREAD

**Issue by TobbeTh** [Sn0wCrack/ExHentai-Archive#16]
The send to archive button does not show up in the search result page, but it does show up when you go in to a specifik gallery. And I have cycled through all watch options on the search page (thumbnail, minimal, e.t.c.).

**Comment by Sn0wCrack** [comment]
Looks like they changed the HTML on that section, seems there's more info there now too, might be hard to squeeze that in.

I'll see what I can do when I have some time.

**Comment by TobbeTh** [comment]
Okay, thanks for the awnser.

**Comment by Sn0wCrack** [comment]
Just pushed something that should fix this.

**Comment by TobbeTh** [comment]
The send to archive does still not show up in the search results page, but it now shows if a archive has been archived by turning it green and writing archived on the search result page.
Updated the script by copy pasting it in to tampermonkey.

**Comment by Sn0wCrack** [comment]
Okay, that should hopefully be working now with my latest changes, it'll only show up on Thumbnail view and should look like this:

![image](https://user-images.githubusercontent.com/442287/65367981-98647100-dc29-11e9-9178-38f221518dc7.png)

**Comment by TobbeTh** [comment]
Thank you, it now works as it should.
